name: Run action at Linux

on:
  workflow_dispatch:

jobs:
  case1:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      - uses: ./
        with:
          user: actions-user
      - run: |
          echo "path: $(PWD)"
          echo "Local: $(git config user.name) <$(git config user.email)>"
          echo "Global: (git config --global user.name) <$(git config --global user.email)>"

  case2:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      - uses: ./
        with:
          global: true
          user: github-actions
      - run: |
          echo "path: $(PWD)"
          echo "Local: $(git config user.name) <$(git config user.email)>"
          echo "Global: (git config --global user.name) <$(git config --global user.email)>"

  case3:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          path: myaction
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          path: target
      - uses: ./myaction/
        with:
          path: target
          user: latest-commit
      - run: |
          echo "path: $(PWD)"
          echo "Local: $(git config user.name) <$(git config user.email)>"
          echo "Global: (git config --global user.name) <$(git config --global user.email)>"
